---
title: "Jordan's O'Reilly Data Science Notebook"
output: html_notebook
---

#Chapter One 

# Section - Data Visualization w/ ggplot2

#install tidyverse
install.packages(tidyverse)
library(tidyverse)

#Load MPG Data Set for experimentation
ggplot2::mpg

#To learn more
?mpg

#Create a gpplot
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))

#Graphing Template
ggplot(data = <DATA>) +
  <GEOM_FUNCTION>(mapping = aes(<mappings>))


#Exercises

#1) Run ggplot(data = mpg). What do you see?
ggplot(data = mpg)
#Answer: Nothing, it just loads the data frame. 

#2) How many rows are in mtcars? How many columns?
?mtcars
#Answer:32 observations, which is rows, and 11 variables, which is columns

#3) What does the drv variable describe? Read the help for ?mpg to find out.
?mpg
#Answer: f = front-wheel drive, r = rear wheel drive, 4 = 4wd

#4) Make a scatterplot of hwy vs cyl
#Answer:
ggplot(data = mpg) +
  geom_point(mapping = aes(x = cyl, y = hwy))

#5) What happens if you make a scatterplot of calss vs drv? 
#Answer: They are both dimensions/categorical variables and are not related to each other in any way. 
ggplot(data = mpg) +
  geom_point(mapping = aes(x = drv, y = class))

# Section - Aesthetic Mappings

#Note: Aesthetics are properties of objects of plot, "a level"

#Example 1
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))

#Example 2 - Size 
#don't map discrete variables to size
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
  
#Example 3 - Alpha/shape aesthetic examples 
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
  
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
  
#Note: Aesthetic aes() function gathers mappings used by a layer and pases them to layer's mapping argument

#If you move arguments outside aes(), it sets properties manually. See example below. 

#Example
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")

#Exercises

#1) What's gone wrong with this code? Why are points not blue?
ggplot(data = mpg) + 
  geom_point(
    mapping = aes(x = displ, y =hwy, color = "blue")
  )
#Answer: Color needs to be outside the aes() function, right now it takes blue as a discrete variable to be passed. The correct code is below: 
ggplot(data = mpg) + 
  geom_point(
    mapping = aes(x = displ, y =hwy), color = "blue"
  )
  
#2) Which variables in mpg are categorical? Which variables are continuous? How can you see this information?

#Answer:First, you use ?mpg to find the variables, there are 11 after running it. Discrete = only in full integers, continuous = can be in decimals. 
?mpg
# The folloiwng are continuous: cty, hwy
# The following are discrete: model, displ, year, cyl, type of transmission, drv, fl and class

#3) Map a continuous variable to color, size and shape. How do these aesthetics behave differently for categoircal versus continuous variables?
ggplot(data = mpg) + 
  geom_point(
    mapping = aes(x = displ, y = hwy, color = hwy)
  )
#Answer: The difference is for discrete variables, each gets a specific category of color. In continuous variables, this becomes a spectrum, each does not get it's own color. Example above. 

#4) What happens if you map the same variable to multiple aesthetics?
ggplot(data = mpg) + 
  geom_point(
    mapping = aes(x = displ, y = displ)
  )
#Answer: The answer becomes a linear y = x plot, because both x and y values are the same. 

#5) What does the stroke aesthetic do? WHat shapes does it work with?
?geom_point
ggplot(data = mpg) + 
  geom_point(
    mapping = aes(x = displ, y = hwy, shape = class, stroke = 2)
  )
#Answer: Stroke helps you increase or decrease the size of each specific plotted point on the graph and works with up to 6 discrete values. 

#6) What happens if you map an aesthetic to something other than a variable name, like aes(color = displ < 5)
ggplot(data = mpg) + 
  geom_point(
    mapping = aes(x = displ, y = hwy, color = displ < 5))
    
#Answer: It does not work because it treats the equation as a T/F binary question.  


# Section - Facets

#To Facet your plot by a single variable, use facet_wrap(). Use a . if you dont want to face in rows/columns, e.g. facet_grid(. ~ cyl)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
  
#To Facet by two variables, add facet_grid()
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y= hwy)) + 
  facet_grid(drv ~ cyl)
  
#Exercises

#1) What happens if you facet on a continuous variable?
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ hwy, nrow = 2)

#Answer:It works, but labels each facet as one of the continuous numbers, leading to a large data set and not helpful.

#2) What do the empty cells in a plot with facet_grid(drv ~ cyl) mean? How do they relate to this plot?
ggplot(data = mpg) +
  geom_point(mapping = aes(x =drv, y = cyl)) +
  facet_grid(drv ~ cyl)
  
#Answer: The empty cells means there is no data available in that facet for those sets of measurements. 

#3) What plots does the following code make? What does . do? 

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)
  
#Answer: This first code puts the facet (in this case drv) on the y axis, cutting the data across displacement and highway for the three DRV modes. It splits the data horizontally

ggplot(data = mpg) + 
  geom_point(mapping = aes(displ, y = hwy)) +
  facet_grid(. ~ cyl)
  
#Answer: Unlike the previous iteration, this splits the data vertically, as the cyl categories are on the vertical X axis. 

#Answer: Using a period effectively allows you not to facet in each row and column and instead across all them. It combines the graphs of all of them.

#4) Take the first faceted plot in this section:

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
  
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))

#Q: What are advantages to using faceting instead of the color aesthetic? Disadvantages? How might balance change if you had a larger data set?

#Answer: I would use color for a larger data set in order to discern color groupings easier, for things such as trends. For smaller data sets, facets are nice, especially if you need to look at discrepancies within each grouping in comparison to a more holistic look.

#5) Read ?facet_wrap. What does nrow do? WHat does ncol do? What other options control the layout of the indivdual panels? Why doesn't facet_grid() have nrow and ncol?
?facet_wrap

#Answer: Nrow and Ncol designate the number of rows and columns in a facet. There are several different options, including surnk (which fits the outputs), switch, which switches x and y from top or bottom. Facet_grid() does not have a designator because it automatically adjusts based on the variable. For example, if Drv has four variables, it will only include four rows or columns.

#6) When using facet_grid() you should usually put the variable with more unique levels in the columns. Why?

ggplot(data = mpg) +
  geom_point(mapping = aes(x =drv, y = cyl)) +
  facet_grid(cyl ~ drv)

ggplot(data = mpg) +
  geom_point(mapping = aes(x =drv, y = cyl)) +
  facet_grid(drv ~ cyl)

#Answer: Humans read top to bottom, and having more unique columns makes the chart easier to read versus having them in the rows. See the two lines of code above to see for yourself. 
# Section - Geometric Objects

# A geom is the geometrical object that a plot uses to represent data. Bar charts use bar geoms, line charts use line geoms, box plots use boxplot geoms etc. Look at the below difference between the two lines of code. 

# left
ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y = hwy)) 
  
# right
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y= hwy))
  
# While you cannot set a shape of a line (but can a point), you can set a linetype of a line. See below for 3 lines that separate out based on values of DRV, 4/f/r:

ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))

# One Geom
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy)) 

# One geom - grouped function
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv)) 

#One geom - using color as a grouping
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, color = drv), 
  show.legend = FALSE
  )
    
#You can also map multiple geoms to a specific set of data. See below, this shows both the geom points of the data set and a line going through them. 

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))
  
# To simplify, map your x and y variables in the global section so you do not need to duplicate code. See same code above, simplified below.

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() +
  geom_smooth()
  
# You can also add on specifications to specific layers that override the global settings. Below we add color to the class for the points only. 

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) +
  geom_smooth()
  
# Below, we filter out the data to only show the line for subcompact.

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) +
  geom_smooth(
  data = filter(mpg, class == "subcompact"),
  se = FALSE
  )
  
# Exercises

#1) What Geom would use use to draw a line chart? A boxplot? A histogram? An area chart?

#Answer: See below

# Line chart (geom_smooth)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_smooth()
  
# Boxplot (geom_boxplot)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_boxplot()
  
# Histogram (geom_histogram)
ggplot(data = mpg, mapping = aes(x = displ)) + 
  geom_histogram()
  
# Area
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_area()
  
#2) Run this code in your head and predict what the output would look like. Then run the code in R and check your predictions:

ggplot(data = mpg,
  mapping = aes(x = displ, y= hwy, color = drv)) +
  geom_point() +
  geom_smooth(se = FALSE)
  
#Assumption: I think that it would produce a scatterplot with point and a line through it. SE I believe might stand for standard deviation, so this just shows a line, rather than the shade of SE for the line. 

#Answer: I forgot, it will categorize the lines as DRV, so there are three lines that are colored. 

#3) What does show.legend = FALSE do? What happens if you remove it? Why do you think I used it earlier in the chapter?

ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, color = drv), 
  show.legend = FALSE
  )

#Answer: Show legend shows a legend on the right side of the graph for the categories you have chosen to group. If you remove it, you still have your graph, but no longer a key/legend on the right hand side. To show the impages without crowding the image with the specific key.

#4) What does the se argument to geom_smooth() do? 

#Answer: As proved earlier it shows the standard deviation of all the points through the line, both above and below the line of best fit. 

#5) Will these two graphs look different? Why/ Why Not? 

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()

ggplot() + 
  geom_point(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
  ) + 
  geom_smooth(
  data = mpg,
  mapping = aes(x= displ, y = hwy)
  )
    
#Answer: Before running the code, I believe they will look the same. The only difference is that in the latter, the variables are mapped locally and so will both need to be changed for the visualization to change. AFTER - my hypothesis was correct, they are the same.

#6) Re-create the R code necessary to generate the images in this book (not shown).

#1
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth(
  se = FALSE
  )

#2 
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, class = drv)) + 
  geom_point() + 
  geom_smooth(se = FALSE)

#3
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, class = drv, color = drv)) + 
  geom_point() + 
  geom_smooth(se = FALSE)
  
#4
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(class = drv, color = drv)) + 
  geom_smooth(se = FALSE)

#5 
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, class = drv, linetype = drv)) + 
  geom_point(mapping = aes(color = drv)) + 
  geom_smooth(se = FALSE)
  
#6 
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, class = drv)) + 
  geom_point(mapping = aes(color = drv)) 
  
  
# Section - Statistical Transformations

#Visualizing diamonds in bar chart and since we did not designate a Y number, atuomtically calculates new values. 
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))

# Bar charts/histograms and frequency polygons bin data and then plot bin counts, number of points that fall into each bin. This is called a stat - statistical transformation
# To learn which stat a geom uses, use the ?geom_ function, like ?geom_bar. 
# Smoothers fit a model to your data and then plot predictions from the model. 
# Boxplots compute a robust summary of the distribution and display a specially formatted box. 

# You can use stats and geoms interchangeably. Previous plot using stat_count(). Every stat has a default geom and every geom has a default stat.
ggplot(data = diamonds) + 
  stat_count(mapping = aes(x= cut))

#Some cases you will have to override stat. Like using identity to map height of bar, or by proportion, see below. Identity allows for the bar chart to be scaled appropriately based on the values. 
ggplot(data = diamonds) + 
  geom_bar(
  mapping = aes(x= cut, y = ..prop.., group = 1)
  )

# You may want to draw greater attention to statistical transformation in your code. Ex. you might use stat_summary(), which summarizes the y values for each unique x value, to draw attention to the summary that you are computing. You can use the ggplot2 cheat sheet to get a list of stats. 

ggplot(data = diamonds) + 
  stat_summary(
  mapping = aes(x = cut, y = depth),
  fun.ymin = min,
  fun.ymax = max,
  fun.y = median
  )

# Exercises

#1) What is the default geom associated with stat_summary()? How could you rewrite the previous plot to use that geom function instead of the stat function? 

?stat_summary()
?stat_bin

#Answer: You can see this in the usage section. The underlying geom is pointrange. The answer for that question is below

ggplot(data = diamonds) + 
  geom_pointrange(mapping = aes(x=cut, y = depth),
  stat = "summary",
   fun.ymin = min,
  fun.ymax = max,
  fun.y = median
  )

#2) What does geom_col() do? How is it different to geom_bar()?

?geom_col
?geom_bar

ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))
  
ggplot(data = diamonds) + 
  geom_col(mapping = aes(x = cut, y = depth))
  

# Answer: Using the ? function we can read about the difference between the two. Geom_Bar makes the height of bar proportional to the number of cases in each group. If you want the height of the bars to represent values in the data, use geom_col instead. 

#3) Most geoms and stats come in pairs that are almost always used in concert. Read through the documentation and make a list of all the pairs. What do they have in common.

#Answer: Documentation: https://ggplot2.tidyverse.org/reference/

#4) What variables does stat_smooth() compute? What parameters control its behavior?

?stat_smooth()

#Answer: Using the ?, we can see it computes predicted values (y), lower pointwise confidence intervals around the mean (ymin), upper pointwise confidence interval around the mean (ymax), and standard error (se)
  
#5) In our proportion bar chart, we need to set group = 1. Why? In other words what is the problem with these two graphs?

?geom_bar()

ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x= cut, y = ..prop..))

ggplot(data = diamonds) + 
  geom_bar(
  mapping = aes(x = cut, fill = color, y = ..prop..)
  )
  
#Correct
ggplot(data = diamonds) + 
  geom_bar(
  mapping = aes(x = cut, fill = color, y = y = depth, group = 1)
  )

  

#Answer: Group is a dummy grouping to override the default behavior, which is to group by the x variable. This allows the data to be propportionally split between all the cuts. Prop stands for proportion and it is automatically set at 1. Using group overrides prop and makes each bar grouped by COUNT percentage, with prop still as X axis. 



# Section - Position Adjustments

#You can color a bar chart using either color or aesthetic

#Color
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x= cut, color = cut))
  
#Fill
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))

#If you use a fill aesthetic with another variable like clarity, bars are automatically stacked. 

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x=  cut, fill = clarity))
  
#If you dont want a stacked bar chart, you can use "identity", "Dodge", or "fill".

#Position = "Identity" will place each object exactly where it falls into the context of the graph. Not useful for bars b/c it overlaps them. To see overlapping, we either need to make bars slightly transparent by setting alpha to a small value, or completely transparent by setting fill = NA. 
  
ggplot(
  data = diamonds,
  mapping = aes(x = cut, fill = clarity)
) + 
  geom_bar(alpha = 1/5, position = "identity")
ggplot(
  data = diamonds,
  mapping = aes(x = cut, color = clarity)
) + 
  geom_bar(fill = NA, position = "identity")
  
# The identity position adjustment is more useful for 2D geoms, like points, where it is default. 

# Position = "fill" works like stacking, but makes each set of stacked bars the same height. This makes it easier to compare proportions across groups. 

ggplot(data = diamonds) +
  geom_bar(
    mapping = aes(x = cut, fill = clarity),
    position = "fill"
)

# Position = "Dodge" places overlapping objects directly beside one another. This makes it easier to compare individual values. 

ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = clarity),
    position = "dodge"
  )
  
# Position = "Jitter" is useful for scatterplots to see a small amount of random noise to each point Spreads the points out because  no two points are likely to receive the same amount of random noise. 

# Without Jitter
ggplot(data = mpg) + 
  geom_point(
    mapping = aes(x= displ, y = hwy))
# With Jitter
ggplot(data = mpg) + 
  geom_point(
    mapping = aes(x= displ, y = hwy),
    position = "jitter"
  )
  
  
#Exercises

#1) What is the problem with this plot? How could you improve it?

ggplot(data = mpg, mapping = aes(x = cty, y= hwy)) + 
  geom_point()
  
#Answer: The first problem is that it is mapping two dependent variables, city and hwy. Both should be mapped individually to something else, such as engine size. In terms of the actual problem with the graph, I think we can include Jitter in order to make the data showcase clusters. There is overplotting b/c multiple observations for each grouping. 

#Jitter
ggplot(data = mpg, mapping = aes(x = cty, y= hwy)) + 
  geom_point(position = "jitter")
  
  
#2) What parameters to geom_jitter() control the amount of jittering?

?geom_jitter()
  
# Answer: Width and height control vertical and horizontal jitter. 

#3) Compare and contrast geom_jitter() and geom_count()

#Jitter
ggplot(data = mpg, mapping = aes(x = cty, y= hwy)) + 
  geom_jitter()

#Count
ggplot(data = mpg, mapping = aes(x = cty, y= hwy)) + 
  geom_count()

#Answer: Jitter geom is just a convenient shortcut for geom_point (position = "jitter"). Geom_count is a variant of geom_point. Geom_count or jitter is usually more approriate than geom_point. For geom_count, points with more observations will be larger than those with fewer observations, and this isn't the case with geom_jitter. 

#4) What's the default position adjustment for geom_boxplot()? Create a visualization of the mpg dataset that demostrates it. 

?geom_boxplot()

ggplot(data = mpg, mapping = aes(x = drv, y = hwy, color = class)) + 
  geom_boxplot()
  
#Answer: A boxplot displays distribution of a continuous variable. It visualizes five summary statistics, median, two hinges and two whiskers, and outlying points individually. It looks like the defualt position is dodge - which puts overlapping objects beside one another.

#Section - Coordinate Systems

# The default coordinate system is cartesian coordinate system. Others include:

#Cooord_flip() switches x and why axis. Useful if you want horizontal boxplots/long labels. 

#Without coord flip
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot()

#With coord flip
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot() + 
  coord_flip()

# There is also coord_quickmap() which sets aspect ratio correctly for maps. Important for plotting spatial data, such as places. 

install.packages("maps")

nz <- map_data("nz")

ggplot(nz, aes(long, lat, group = group)) + 
  geom_polygon(fill = "white", color = "black")
  
ggplot(nz, aes(long, lat, group = group)) + 
  geom_polygon(fill = "white", color = "black") + 
  coord_quickmap()

# Coord_polar() uses polar coordinates. Polar coordinates reveal an interesting connection between a bar chart and a coxcomb cahrt. 

bar <- ggplot(data = diamonds) +
  geom_bar(
  mapping = aes(x = cut, fill = cut),
  show.legend = FALSE,
  width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

#Coord flip
bar + coord_flip()

#Coord polar
bar + coord_polar()


#Exercises

#1) Turn a stacked bar chart into a pie chart using coord_polar()

#Answer: 

#Stacked bar chart - using x = factor(1) makes it so you do not need an x variable, or only put one variable there.
stacked_chart <- ggplot(data = diamonds) + 
  geom_bar(
  mapping = aes(x = factor(1), fill = cut),
  position = "fill"
  )
  
#Pie Chart
stacked_chart + coord_polar(theta = "y")
#Theta = Y allows for the pie chart. Without the Y, it simply becomes a bullseye. See below.

#Bullseye
stacked_chart + coord_polar()

#2) WHat does labs() do? Read the documentation.

?labs()

# Answer: Labs essentially allows you to display the full variable name, on both the axes. 

#3) What's the difference between coord_quickmap() and coord_map()

?coord_quickmap()
?coord_map()

# Answer: Coord map projects a portion of the earth onto a flat 2d plane. This does not preserve straight lines and requires computation. Quickmap requires far less computation and preserves lines. This means it is better for smaller areas closer to the equator. 

#4) What does the following plot tell you about the relationship between city and highway MPG? Why is coord_fixed() important? What does geom_abline() do?

ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_point() + 
  geom_abline() + 
  coord_fixed()
  
# Without coord_fixed
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_point() + 
  geom_abline() 
  
#Answer: Coord_fixed allows you to keep a consistent X/Y ratio, reducing "zoom" into the picture to fit/scale and makes larger scatterplots easier to read. 

#Without geom_abline()
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_point() + 
  coord_fixed()
  
?geom_abline()
#geom_abline() plots a straight line through your data, essentially a reference line. 